### ISSUE TITLE
identify unique reactions in iKS1317 and Sco4

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/Streptomyces_coelicolor-GEM#6]
- [ ] ensure that Sco4 and iKS1317 metabolites are in the same namespace as much as possible (#7)
- [ ] identify reactions that are present in Sco4, but not iKS1317
- [ ] ensure that new metabolites and annotations are in the same format as in iKS1317
- [ ] add reactions to iKS1317

**Comment by sulheim** [comment]
Current status of reaction mapping. 432 of the reactions in Sco4 not mapped to any reaction in iKS1317.
[matched reactions Sco4.xlsx](https://github.com/SysBioChalmers/Streptomyces_coelicolor-GEM/files/2192373/matched.reactions.Sco4.xlsx)
